# Generated by Django 5.2.7 on 2025-10-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='notes',
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hard cover'), ('ebook', 'E-Book'), ('audiobook', 'Audiobook')], default='hc', max_length=12),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('classic', 'Classic'), ('romantic', 'Romantic'), ('comic', 'Comic'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('educational', 'Educational')], default='cl', max_length=12),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0, help_text='in US dollars $'),
            preserve_default=False,
        ),
    ]
