# Generated by Django 5.2.7 on 2025-10-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
