# Generated by Django 5.2.7 on 2025-10-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='sales'),
        ),
    ]
